ALTER TABLE member ADD COLUMN IF NOT EXISTS provider VARCHAR(50);
ALTER TABLE member ADD COLUMN IF NOT EXISTS provider_id VARCHAR(255);
ALTER TABLE member ALTER COLUMN password DROP NOT NULL;
ALTER TABLE member ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(500);
