// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package analysis

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"bytes"
	"github.com/yuin/goldmark"
)

func parseMarkdown(source string) string {
	var buf bytes.Buffer
	if err := goldmark.Convert([]byte(source), &buf); err != nil {
		return source
	}
	return buf.String()
}

func LinguisticModal(name string, analysis string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"modal-header\"><h2 class=\"modal-header-title\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z\"></path> <path d=\"M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z\"></path></svg> ภาษาศาสตร์ของ \"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/analysis/linguistic_modal.templ`, Line: 23, Col: 50}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"</h2><button class=\"close-btn\" onclick=\"document.getElementById('linguistic-modal-container').style.display='none'\">&times;</button></div><div class=\"modal-body gemini-content linguistic-content\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw(parseMarkdown(analysis)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><style>\n\t\t.linguistic-content {\n\t\t\tfont-family: 'Sarabun', sans-serif;\n\t\t\tcolor: #2d3748;\n\t\t\tline-height: 1.8;\n\t\t}\n\t\t.linguistic-content h1, \n\t\t.linguistic-content h2, \n\t\t.linguistic-content h3 {\n\t\t\tfont-family: 'Sarabun', sans-serif;\n\t\t\tfont-weight: 700;\n\t\t\tcolor: #1a202c;\n\t\t\tmargin-top: 1.5em;\n\t\t\tmargin-bottom: 0.8em;\n\t\t}\n\t\t.linguistic-content h1 { font-size: 1.8rem; }\n\t\t.linguistic-content h2 { font-size: 1.5rem; border-bottom: 2px solid #edf2f7; padding-bottom: 0.5rem; }\n\t\t.linguistic-content h3 { font-size: 1.25rem; }\n\t\t.linguistic-content p {\n\t\t\tfont-size: 1rem;\n\t\t\tmargin-bottom: 1.2em;\n\t\t\ttext-align: justify;\n\t\t}\n\t\t.linguistic-content ul, .linguistic-content ol {\n\t\t\tmargin-bottom: 1.2em;\n\t\t\tpadding-left: 1.5em;\n\t\t}\n\t\t.linguistic-content li {\n\t\t\tmargin-bottom: 0.5em;\n\t\t}\n\t\t.linguistic-content strong {\n\t\t\tcolor: #2d3748;\n\t\t\tfont-weight: 700;\n\t\t}\n\t</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
