// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package admin

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func APIDocs() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"container mx-auto px-4 py-8\"><h1 class=\"text-3xl font-bold mb-6 text-gray-800\">API Documentation for Frontend</h1><p class=\"mb-8 text-gray-600\">รายการ API ทั้งหมดสำหรับนำไปพัฒนา Application</p><div class=\"space-y-6\"><!-- Login API --><div class=\"bg-white p-6 rounded-lg shadow-md\"><h2 class=\"text-xl font-semibold mb-2 flex items-center\"><span class=\"bg-blue-100 text-blue-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded\">POST</span> <span class=\"ml-2\">/api/login</span></h2><p class=\"text-gray-700 mb-2\">เข้าสู่ระบบเพื่อรับข้อมูลสมาชิกและสีกระเป๋า</p><p class=\"text-sm text-gray-500 mb-4\">Request Body (JSON)</p><div class=\"bg-gray-50 p-4 rounded border border-gray-200 mb-4\"><pre class=\"text-sm text-gray-800 overflow-x-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(`{
  "username": "your_username",
  "password": "your_password"
}`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/pages/admin/api_docs.templ`, Line: 22, Col: 2}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</pre></div><p class=\"text-sm text-gray-500 mb-4\">Response (JSON)</p><div class=\"bg-gray-50 p-4 rounded border border-gray-200\"><pre class=\"text-sm text-gray-800 overflow-x-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(`{
  "message": "Login successful",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
  "id": 1,
  "username": "user1",
  "email": "user1@example.com",
  "status": 1,
  "is_vip": false,
  "assigned_colors": ["#FF0000", "#00FF00", "#0000FF", "#FFFF00", "#00FFFF"]
}`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/pages/admin/api_docs.templ`, Line: 37, Col: 2}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</pre></div></div><!-- Articles API --><div class=\"bg-white p-6 rounded-lg shadow-md\"><h2 class=\"text-xl font-semibold mb-2 flex items-center\"><span class=\"bg-green-100 text-green-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded\">GET</span> <span class=\"ml-2\">/api/articles</span></h2><p class=\"text-gray-700 mb-4\">ดึงข้อมูลบทความทั้งหมด</p><div class=\"bg-gray-50 p-4 rounded border border-gray-200\"><pre class=\"text-sm text-gray-800 overflow-x-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(`[
  {
    "art_id": 1,
    "slug": "article-slug",
    "title": "Article Title",
    "excerpt": "Short description...",
    "category": "Category",
    "image_url": "/uploads/image.jpg",
    "published_at": "2023-01-01T00:00:00Z",
    "is_published": true
  },
  ...
]`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/pages/admin/api_docs.templ`, Line: 63, Col: 2}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</pre></div></div><!-- Buddhist Days List API --><div class=\"bg-white p-6 rounded-lg shadow-md\"><h2 class=\"text-xl font-semibold mb-2 flex items-center\"><span class=\"bg-green-100 text-green-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded\">GET</span> <span class=\"ml-2\">/api/buddhist-days</span></h2><p class=\"text-gray-700 mb-4\">ดึงรายการวันพระทั้งหมดที่มีในระบบ</p><div class=\"bg-gray-50 p-4 rounded border border-gray-200\"><pre class=\"text-sm text-gray-800 overflow-x-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(`[
  {
    "id": 1,
    "date": "2024-05-22T00:00:00Z"
  },
  ...
]`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/pages/admin/api_docs.templ`, Line: 83, Col: 2}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</pre></div></div><!-- Upcoming Buddhist Day API --><div class=\"bg-white p-6 rounded-lg shadow-md\"><h2 class=\"text-xl font-semibold mb-2 flex items-center\"><span class=\"bg-green-100 text-green-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded\">GET</span> <span class=\"ml-2\">/api/buddhist-days/upcoming</span></h2><p class=\"text-gray-700 mb-4\">ดึงวันพระที่กำลังจะมาถึง (หรือวันนี้) จำนวน 1 วัน</p><div class=\"bg-gray-50 p-4 rounded border border-gray-200\"><pre class=\"text-sm text-gray-800 overflow-x-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(`{
  "id": 5,
  "date": "2024-05-22T00:00:00Z"
}`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/pages/admin/api_docs.templ`, Line: 100, Col: 2}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</pre></div></div><!-- Check Buddhist Day API --><div class=\"bg-white p-6 rounded-lg shadow-md\"><h2 class=\"text-xl font-semibold mb-2 flex items-center\"><span class=\"bg-green-100 text-green-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded\">GET</span> <span class=\"ml-2\">/api/buddhist-days/check</span></h2><p class=\"text-gray-700 mb-2\">ตรวจสอบว่าวันที่ระบุเป็นวันพระหรือไม่</p><p class=\"text-sm text-gray-500 mb-4\">Query Param: <code>date</code> (Optional, default = today) Format: YYYY-MM-DD</p><div class=\"bg-gray-50 p-4 rounded border border-gray-200\"><pre class=\"text-sm text-gray-800 overflow-x-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(`// GET /api/buddhist-days/check?date=2024-05-22
{
  "date": "2024-05-22",
  "is_buddhist_day": true
}`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/pages/admin/api_docs.templ`, Line: 119, Col: 2}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</pre></div></div><!-- Images API --><div class=\"bg-white p-6 rounded-lg shadow-md\"><h2 class=\"text-xl font-semibold mb-2 flex items-center\"><span class=\"bg-green-100 text-green-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded\">GET</span> <span class=\"ml-2\">/api/images</span></h2><p class=\"text-gray-700 mb-4\">ดึงรายชื่อไฟล์รูปภาพทั้งหมดในระบบ</p><div class=\"bg-gray-50 p-4 rounded border border-gray-200\"><pre class=\"text-sm text-gray-800 overflow-x-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 string
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(`[
  "image1.jpg",
  "image2.png",
  ...
]`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/pages/admin/api_docs.templ`, Line: 137, Col: 2}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</pre></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
